@startuml

class Larik {
+ {static} cetak(int[]) : void
+ {static} sequentialSearch(int[], int) : int
+ {static} binarySearch(int[], int) : int
+ {static} interpolationSearch(int[], int) : int
}
@enduml